from typing import Protocol

import numpy as np


class FaceStore(Protocol):
    def upsert(self, face_id: str, vector: np.ndarray) -> None: ...
    def get(self, face_id: str) -> np.ndarray | None: ...
    def delete(self, face_id: str) -> bool: ...
    def search(
        self, vector: np.ndarray, *, limit: int, min_score: float
    ) -> list[tuple[str, float]]: ...
    def ping(self) -> bool: ...
